-- Generated from food-nutrition-admin-manual-review.csv.
-- Review this file before running against the database.
-- Run:
--   psql "$DATABASE_URL" -f prisma/manual/update-food-nutrition-from-review.sql

BEGIN;

CREATE TEMP TABLE food_nutrition_updates (
  id INTEGER PRIMARY KEY,
  category TEXT,
  calories INTEGER NOT NULL,
  protein DOUBLE PRECISION NOT NULL,
  fat DOUBLE PRECISION NOT NULL,
  carbs DOUBLE PRECISION NOT NULL,
  meal_time_tags TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
  meal_roles TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
  goal_tags TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
  cooking_method TEXT,
  portion_type TEXT,
  serving_note TEXT
) ON COMMIT DROP;

INSERT INTO food_nutrition_updates (
  id,
  category,
  calories,
  protein,
  fat,
  carbs,
  meal_time_tags,
  meal_roles,
  goal_tags,
  cooking_method,
  portion_type,
  serving_note
) VALUES
  (
    1,
    'Món nước',
    520,
    28,
    16,
    62,
    ARRAY['BREAKFAST', 'LUNCH']::TEXT[],
    ARRAY['MAIN', 'STAPLE']::TEXT[],
    ARRAY['MAINTENANCE', 'MUSCLE_GAIN']::TEXT[],
    'SOUP',
    'FULL_MEAL',
    '1 tô vừa: bánh phở 180g, bò 90g, nước dùng, rau.'
  ),
  (
    2,
    'Bún',
    650,
    30,
    28,
    72,
    ARRAY['LUNCH', 'DINNER']::TEXT[],
    ARRAY['MAIN', 'STAPLE']::TEXT[],
    ARRAY['MAINTENANCE', 'WEIGHT_GAIN']::TEXT[],
    'GRILLED',
    'FULL_MEAL',
    '1 phần vừa: bún 180g, thịt nướng/chả 120g, nước chấm.'
  ),
  (
    3,
    'Cơm',
    720,
    32,
    28,
    82,
    ARRAY['LUNCH', 'DINNER']::TEXT[],
    ARRAY['MAIN', 'STAPLE']::TEXT[],
    ARRAY['MAINTENANCE', 'WEIGHT_GAIN']::TEXT[],
    'GRILLED',
    'FULL_MEAL',
    '1 đĩa vừa: cơm 180g, sườn 120g, bì/chả ít, nước mắm.'
  ),
  (
    4,
    'Ăn nhẹ',
    390,
    15,
    12,
    56,
    ARRAY['BREAKFAST', 'SNACK']::TEXT[],
    ARRAY['STAPLE', 'SNACK']::TEXT[],
    ARRAY['MAINTENANCE', 'WEIGHT_GAIN']::TEXT[],
    'RAW',
    'FULL_MEAL',
    '1 ổ bánh mì nhân cơ bản, không tính nhiều sốt/bơ.'
  ),
  (
    5,
    'Ăn nhẹ',
    280,
    16,
    7,
    38,
    ARRAY['SNACK', 'LUNCH', 'DINNER']::TEXT[],
    ARRAY['SNACK', 'SIDE']::TEXT[],
    ARRAY['WEIGHT_LOSS', 'MAINTENANCE']::TEXT[],
    'RAW',
    'LIGHT',
    '3 cuốn tôm thịt vừa, ít nước chấm.'
  ),
  (
    6,
    'Bún',
    580,
    28,
    20,
    70,
    ARRAY['BREAKFAST', 'LUNCH']::TEXT[],
    ARRAY['MAIN', 'STAPLE']::TEXT[],
    ARRAY['MAINTENANCE', 'WEIGHT_GAIN']::TEXT[],
    'SOUP',
    'FULL_MEAL',
    '1 tô vừa: bún, bò/chả, nước dùng.'
  ),
  (
    7,
    'Cháo',
    430,
    22,
    18,
    48,
    ARRAY['BREAKFAST', 'DINNER']::TEXT[],
    ARRAY['MAIN', 'STAPLE']::TEXT[],
    ARRAY['MAINTENANCE']::TEXT[],
    'SOUP',
    'FULL_MEAL',
    '1 tô vừa, nội tạng mức vừa.'
  ),
  (
    8,
    'Món khô, Xôi',
    520,
    15,
    14,
    84,
    ARRAY['BREAKFAST']::TEXT[],
    ARRAY['STAPLE']::TEXT[],
    ARRAY['WEIGHT_GAIN', 'MAINTENANCE']::TEXT[],
    'STEAMED',
    'FULL_MEAL',
    '1 gói xôi vừa 250g, đậu xanh, hành phi.'
  ),
  (
    9,
    'Bánh',
    520,
    20,
    26,
    52,
    ARRAY['LUNCH', 'DINNER']::TEXT[],
    ARRAY['MAIN', 'STAPLE']::TEXT[],
    ARRAY['MAINTENANCE', 'WEIGHT_GAIN']::TEXT[],
    'FRIED',
    'FULL_MEAL',
    '1 cái vừa kèm rau, nước chấm.'
  ),
  (
    10,
    'Hủ tiếu, Món nước',
    500,
    25,
    12,
    68,
    ARRAY['BREAKFAST', 'LUNCH']::TEXT[],
    ARRAY['MAIN', 'STAPLE']::TEXT[],
    ARRAY['MAINTENANCE']::TEXT[],
    'SOUP',
    'FULL_MEAL',
    '1 tô hủ tiếu vừa.'
  ),
  (
    11,
    'Cuốn',
    420,
    16,
    12,
    62,
    ARRAY['BREAKFAST', 'SNACK']::TEXT[],
    ARRAY['STAPLE', 'MAIN']::TEXT[],
    ARRAY['MAINTENANCE']::TEXT[],
    'STEAMED',
    'FULL_MEAL',
    '1 phần 250g, chả vừa, nước mắm.'
  ),
  (
    12,
    'Bún',
    480,
    24,
    14,
    62,
    ARRAY['BREAKFAST', 'LUNCH']::TEXT[],
    ARRAY['MAIN', 'STAPLE']::TEXT[],
    ARRAY['MAINTENANCE']::TEXT[],
    'SOUP',
    'FULL_MEAL',
    '1 tô vừa có riêu, đậu, bún.'
  ),
  (
    13,
    'Mì/Miến/Nui',
    560,
    27,
    18,
    70,
    ARRAY['BREAKFAST', 'LUNCH']::TEXT[],
    ARRAY['MAIN', 'STAPLE']::TEXT[],
    ARRAY['MAINTENANCE', 'WEIGHT_GAIN']::TEXT[],
    'SOUP',
    'FULL_MEAL',
    '1 tô vừa, ít dầu đậu phộng.'
  ),
  (
    14,
    'Mì, Món nước',
    530,
    25,
    15,
    72,
    ARRAY['BREAKFAST', 'LUNCH']::TEXT[],
    ARRAY['MAIN', 'STAPLE']::TEXT[],
    ARRAY['MAINTENANCE']::TEXT[],
    'SOUP',
    'FULL_MEAL',
    '1 tô vừa.'
  ),
  (
    15,
    'Món nước, Mì',
    500,
    22,
    12,
    72,
    ARRAY['BREAKFAST', 'LUNCH']::TEXT[],
    ARRAY['MAIN', 'STAPLE']::TEXT[],
    ARRAY['MAINTENANCE']::TEXT[],
    'SOUP',
    'FULL_MEAL',
    '1 tô bánh canh thường.'
  ),
  (
    16,
    'Ăn nhẹ',
    320,
    12,
    20,
    24,
    ARRAY['SNACK', 'DINNER']::TEXT[],
    ARRAY['SNACK', 'SIDE']::TEXT[],
    ARRAY['WEIGHT_GAIN', 'MAINTENANCE']::TEXT[],
    'FRIED',
    'LIGHT',
    '3 cuốn nhỏ, món phụ không nên là bữa chính giảm cân.'
  ),
  (
    17,
    'Món nước, Kho',
    560,
    30,
    20,
    60,
    ARRAY['BREAKFAST', 'LUNCH', 'DINNER']::TEXT[],
    ARRAY['MAIN', 'STAPLE']::TEXT[],
    ARRAY['MAINTENANCE', 'WEIGHT_GAIN']::TEXT[],
    'SOUP',
    'FULL_MEAL',
    '1 tô vừa kèm bánh mì hoặc bún ít.'
  ),
  (
    18,
    'Món nước',
    620,
    30,
    28,
    58,
    ARRAY['LUNCH', 'DINNER']::TEXT[],
    ARRAY['MAIN', 'STAPLE']::TEXT[],
    ARRAY['MAINTENANCE', 'WEIGHT_GAIN']::TEXT[],
    'SOUP',
    'FULL_MEAL',
    '1 phần vừa, có khoai và nước cốt dừa.'
  ),
  (
    19,
    'Món nước',
    520,
    35,
    16,
    50,
    ARRAY['LUNCH', 'DINNER']::TEXT[],
    ARRAY['MAIN', 'SOUP']::TEXT[],
    ARRAY['MAINTENANCE', 'MUSCLE_GAIN']::TEXT[],
    'SOUP',
    'FULL_MEAL',
    '1 khẩu phần cá nhân, tính kèm ít bún.'
  ),
  (
    20,
    'Ăn nhẹ',
    360,
    12,
    8,
    62,
    ARRAY['SNACK', 'BREAKFAST']::TEXT[],
    ARRAY['SNACK', 'STAPLE']::TEXT[],
    ARRAY['MAINTENANCE']::TEXT[],
    'STEAMED',
    'LIGHT',
    '8-10 cái vừa, ít nước mắm.'
  ),
  (
    21,
    'Ăn nhẹ',
    380,
    12,
    10,
    60,
    ARRAY['BREAKFAST', 'SNACK']::TEXT[],
    ARRAY['STAPLE', 'SNACK']::TEXT[],
    ARRAY['MAINTENANCE']::TEXT[],
    'STEAMED',
    'LIGHT',
    '1 phần 8-10 chén nhỏ.'
  ),
  (
    22,
    'Món khô',
    420,
    15,
    10,
    68,
    ARRAY['BREAKFAST']::TEXT[],
    ARRAY['STAPLE', 'MAIN']::TEXT[],
    ARRAY['MAINTENANCE']::TEXT[],
    'STEAMED',
    'FULL_MEAL',
    '1 phần vừa kèm chả.'
  ),
  (
    23,
    'Bánh',
    460,
    18,
    12,
    70,
    ARRAY['BREAKFAST', 'LUNCH']::TEXT[],
    ARRAY['STAPLE', 'MAIN']::TEXT[],
    ARRAY['MAINTENANCE']::TEXT[],
    'STEAMED',
    'FULL_MEAL',
    '1 phần vừa kèm thịt/rau.'
  ),
  (
    24,
    'Bún',
    620,
    32,
    20,
    76,
    ARRAY['LUNCH']::TEXT[],
    ARRAY['MAIN', 'STAPLE']::TEXT[],
    ARRAY['MAINTENANCE', 'WEIGHT_GAIN']::TEXT[],
    'SOUP',
    'FULL_MEAL',
    '1 tô vừa, mặn cao nên hạn chế.'
  ),
  (
    25,
    'Bún',
    720,
    28,
    34,
    72,
    ARRAY['LUNCH', 'DINNER']::TEXT[],
    ARRAY['MAIN', 'STAPLE']::TEXT[],
    ARRAY['WEIGHT_GAIN', 'MAINTENANCE']::TEXT[],
    'FRIED',
    'FULL_MEAL',
    '1 mẹt cá nhân, đậu chiên và mắm tôm.'
  ),
  (
    26,
    'Ăn nhẹ',
    180,
    14,
    9,
    10,
    ARRAY['SNACK']::TEXT[],
    ARRAY['SNACK']::TEXT[],
    ARRAY['MAINTENANCE']::TEXT[],
    'RAW',
    'LIGHT',
    '2-3 cái nhỏ, natri cao.'
  ),
  (
    27,
    'Tráng miệng',
    320,
    5,
    8,
    58,
    ARRAY['SNACK']::TEXT[],
    ARRAY['DESSERT']::TEXT[],
    ARRAY['WEIGHT_GAIN', 'MAINTENANCE']::TEXT[],
    'RAW',
    'LIGHT',
    '1 ly/chén vừa, đường cao.'
  ),
  (
    28,
    'Tráng miệng',
    120,
    6,
    3,
    17,
    ARRAY['SNACK', 'DESSERT']::TEXT[],
    ARRAY['SNACK', 'DESSERT']::TEXT[],
    ARRAY['WEIGHT_LOSS', 'MAINTENANCE', 'MUSCLE_GAIN']::TEXT[],
    'RAW',
    'LIGHT',
    '1 hũ 100-120g, ít đường.'
  ),
  (
    29,
    'Tráng miệng',
    180,
    2,
    1,
    42,
    ARRAY['SNACK', 'DESSERT']::TEXT[],
    ARRAY['DESSERT', 'SNACK']::TEXT[],
    ARRAY['WEIGHT_LOSS', 'MAINTENANCE']::TEXT[],
    'RAW',
    'LIGHT',
    '1 dĩa 200g trái cây tươi.'
  ),
  (
    30,
    'Đồ uống',
    160,
    3,
    4,
    28,
    ARRAY['BREAKFAST', 'SNACK']::TEXT[],
    ARRAY['DRINK']::TEXT[],
    ARRAY['MAINTENANCE']::TEXT[],
    'RAW',
    'LIGHT',
    '1 ly vừa, sữa đặc vừa.'
  ),
  (
    32,
    'Phở',
    470,
    28,
    10,
    62,
    ARRAY['BREAKFAST', 'LUNCH']::TEXT[],
    ARRAY['MAIN', 'STAPLE']::TEXT[],
    ARRAY['WEIGHT_LOSS', 'MAINTENANCE', 'MUSCLE_GAIN']::TEXT[],
    'SOUP',
    'FULL_MEAL',
    '1 tô vừa, gà bỏ da.'
  ),
  (
    35,
    'Bánh mì',
    430,
    20,
    18,
    52,
    ARRAY['BREAKFAST']::TEXT[],
    ARRAY['MAIN', 'STAPLE']::TEXT[],
    ARRAY['MAINTENANCE', 'WEIGHT_GAIN']::TEXT[],
    'FRIED',
    'FULL_MEAL',
    '1 ổ + 1-2 trứng, ít sốt.'
  ),
  (
    36,
    'Bánh mì',
    480,
    28,
    16,
    56,
    ARRAY['BREAKFAST', 'LUNCH']::TEXT[],
    ARRAY['MAIN', 'STAPLE']::TEXT[],
    ARRAY['MAINTENANCE', 'WEIGHT_GAIN']::TEXT[],
    'GRILLED',
    'FULL_MEAL',
    '1 ổ với 100g gà nướng.'
  ),
  (
    37,
    'Cơm',
    200,
    4,
    0.5,
    45,
    ARRAY['LUNCH', 'DINNER']::TEXT[],
    ARRAY['STAPLE']::TEXT[],
    ARRAY['WEIGHT_LOSS', 'MAINTENANCE', 'WEIGHT_GAIN', 'MUSCLE_GAIN']::TEXT[],
    'STEAMED',
    'COMPONENT',
    '150g cơm trắng chín.'
  ),
  (
    38,
    'Cơm',
    580,
    36,
    12,
    78,
    ARRAY['LUNCH', 'DINNER']::TEXT[],
    ARRAY['MAIN', 'STAPLE']::TEXT[],
    ARRAY['WEIGHT_LOSS', 'MAINTENANCE', 'MUSCLE_GAIN']::TEXT[],
    'BOILED',
    'FULL_MEAL',
    '150g cơm + 120g gà luộc bỏ da + rau.'
  ),
  (
    39,
    'Cơm',
    700,
    35,
    24,
    82,
    ARRAY['LUNCH', 'DINNER']::TEXT[],
    ARRAY['MAIN', 'STAPLE']::TEXT[],
    ARRAY['MAINTENANCE', 'WEIGHT_GAIN', 'MUSCLE_GAIN']::TEXT[],
    'GRILLED',
    'FULL_MEAL',
    '150g cơm + 120g gà nướng có ướp/sốt.'
  ),
  (
    40,
    'Cơm',
    680,
    34,
    24,
    78,
    ARRAY['LUNCH', 'DINNER']::TEXT[],
    ARRAY['MAIN', 'STAPLE']::TEXT[],
    ARRAY['MAINTENANCE', 'WEIGHT_GAIN']::TEXT[],
    'STIR_FRIED',
    'FULL_MEAL',
    '150g cơm + 120g bò xào rau.'
  ),
  (
    41,
    'Canh',
    220,
    24,
    6,
    18,
    ARRAY['LUNCH', 'DINNER']::TEXT[],
    ARRAY['SOUP', 'SIDE']::TEXT[],
    ARRAY['WEIGHT_LOSS', 'MAINTENANCE']::TEXT[],
    'SOUP',
    'COMPONENT',
    '1 tô canh cá 300ml.'
  ),
  (
    42,
    'Canh',
    160,
    6,
    4,
    26,
    ARRAY['LUNCH', 'DINNER']::TEXT[],
    ARRAY['SOUP', 'SIDE']::TEXT[],
    ARRAY['WEIGHT_LOSS', 'MAINTENANCE']::TEXT[],
    'SOUP',
    'COMPONENT',
    '1 tô 300ml, bí đỏ và ít thịt/tôm.'
  ),
  (
    43,
    'Canh',
    90,
    6,
    2,
    12,
    ARRAY['LUNCH', 'DINNER']::TEXT[],
    ARRAY['SOUP', 'SIDE']::TEXT[],
    ARRAY['WEIGHT_LOSS', 'MAINTENANCE']::TEXT[],
    'SOUP',
    'COMPONENT',
    '1 tô rau cải 300ml.'
  ),
  (
    44,
    'Xào',
    320,
    36,
    18,
    2,
    ARRAY['LUNCH', 'DINNER']::TEXT[],
    ARRAY['MAIN']::TEXT[],
    ARRAY['WEIGHT_LOSS', 'MAINTENANCE', 'MUSCLE_GAIN']::TEXT[],
    'STIR_FRIED',
    'COMPONENT',
    '120g thịt gà áp chảo, ít dầu.'
  ),
  (
    45,
    'Hấp',
    240,
    34,
    8,
    3,
    ARRAY['LUNCH', 'DINNER']::TEXT[],
    ARRAY['MAIN']::TEXT[],
    ARRAY['WEIGHT_LOSS', 'MAINTENANCE', 'MUSCLE_GAIN']::TEXT[],
    'STEAMED',
    'COMPONENT',
    '120g gà bỏ da hấp gừng.'
  ),
  (
    46,
    'Rau',
    360,
    36,
    12,
    24,
    ARRAY['LUNCH', 'DINNER']::TEXT[],
    ARRAY['MAIN', 'SIDE']::TEXT[],
    ARRAY['WEIGHT_LOSS', 'MAINTENANCE', 'MUSCLE_GAIN']::TEXT[],
    'RAW',
    'FULL_MEAL',
    '120g ức gà + rau + ít sốt.'
  ),
  (
    47,
    'Rau',
    390,
    32,
    16,
    26,
    ARRAY['LUNCH', 'DINNER']::TEXT[],
    ARRAY['MAIN', 'SIDE']::TEXT[],
    ARRAY['WEIGHT_LOSS', 'MAINTENANCE', 'MUSCLE_GAIN']::TEXT[],
    'RAW',
    'FULL_MEAL',
    'Cá ngừ + rau + ít sốt, 1 tô lớn.'
  ),
  (
    48,
    'Tráng miệng',
    260,
    12,
    6,
    42,
    ARRAY['BREAKFAST', 'SNACK']::TEXT[],
    ARRAY['SNACK', 'DESSERT']::TEXT[],
    ARRAY['WEIGHT_LOSS', 'MAINTENANCE']::TEXT[],
    'RAW',
    'LIGHT',
    'Sữa chua 120g + yến mạch 35g.'
  ),
  (
    49,
    'Cháo, Bổ dưỡng',
    300,
    14,
    8,
    44,
    ARRAY['BREAKFAST', 'DINNER']::TEXT[],
    ARRAY['MAIN', 'STAPLE']::TEXT[],
    ARRAY['WEIGHT_LOSS', 'MAINTENANCE']::TEXT[],
    'SOUP',
    'FULL_MEAL',
    'Yến mạch 50g nấu cháo, thêm đạm nhẹ.'
  ),
  (
    50,
    'Ăn nhẹ',
    180,
    3,
    0.3,
    41,
    ARRAY['BREAKFAST', 'SNACK']::TEXT[],
    ARRAY['STAPLE', 'SNACK']::TEXT[],
    ARRAY['WEIGHT_LOSS', 'MAINTENANCE']::TEXT[],
    'BOILED',
    'COMPONENT',
    '200g khoai lang luộc.'
  ),
  (
    51,
    'Nướng, Chay',
    210,
    5,
    4,
    40,
    ARRAY['LUNCH', 'DINNER', 'SNACK']::TEXT[],
    ARRAY['STAPLE', 'SIDE']::TEXT[],
    ARRAY['MAINTENANCE']::TEXT[],
    'GRILLED',
    'COMPONENT',
    '200g khoai tây nướng ít dầu.'
  ),
  (
    52,
    'Cơm',
    620,
    35,
    22,
    68,
    ARRAY['LUNCH', 'DINNER']::TEXT[],
    ARRAY['MAIN', 'STAPLE']::TEXT[],
    ARRAY['MAINTENANCE', 'MUSCLE_GAIN']::TEXT[],
    'GRILLED',
    'FULL_MEAL',
    '150g gạo lứt + 120g cá hồi + rau.'
  ),
  (
    53,
    'Cơm',
    540,
    38,
    10,
    68,
    ARRAY['LUNCH', 'DINNER']::TEXT[],
    ARRAY['MAIN', 'STAPLE']::TEXT[],
    ARRAY['WEIGHT_LOSS', 'MAINTENANCE', 'MUSCLE_GAIN']::TEXT[],
    'BOILED',
    'FULL_MEAL',
    'Tên DB có thể sai chính tả: cơm gạo lứt ức gà.'
  ),
  (
    54,
    'Mì/Miến/Nui',
    430,
    27,
    8,
    62,
    ARRAY['BREAKFAST', 'LUNCH', 'DINNER']::TEXT[],
    ARRAY['MAIN', 'STAPLE']::TEXT[],
    ARRAY['WEIGHT_LOSS', 'MAINTENANCE']::TEXT[],
    'SOUP',
    'FULL_MEAL',
    '1 tô miến gà vừa.'
  ),
  (
    55,
    'Hủ tiếu',
    560,
    30,
    16,
    72,
    ARRAY['BREAKFAST', 'LUNCH']::TEXT[],
    ARRAY['MAIN', 'STAPLE']::TEXT[],
    ARRAY['MAINTENANCE']::TEXT[],
    'SOUP',
    'FULL_MEAL',
    '1 tô vừa có tôm/thịt.'
  ),
  (
    57,
    'Bún',
    480,
    30,
    10,
    66,
    ARRAY['BREAKFAST', 'LUNCH']::TEXT[],
    ARRAY['MAIN', 'STAPLE']::TEXT[],
    ARRAY['WEIGHT_LOSS', 'MAINTENANCE']::TEXT[],
    'SOUP',
    'FULL_MEAL',
    '1 tô bún cá vừa.'
  ),
  (
    60,
    'Mì/Miến/Nui',
    680,
    32,
    24,
    82,
    ARRAY['LUNCH', 'DINNER']::TEXT[],
    ARRAY['MAIN', 'STAPLE']::TEXT[],
    ARRAY['MAINTENANCE', 'WEIGHT_GAIN']::TEXT[],
    'STIR_FRIED',
    'FULL_MEAL',
    '1 đĩa mì xào, dầu mức vừa.'
  ),
  (
    61,
    'Kho',
    310,
    28,
    18,
    8,
    ARRAY['LUNCH', 'DINNER']::TEXT[],
    ARRAY['MAIN']::TEXT[],
    ARRAY['MAINTENANCE', 'MUSCLE_GAIN']::TEXT[],
    'BRAISED',
    'COMPONENT',
    '120g cá thu kho, chưa tính cơm.'
  ),
  (
    63,
    'Hấp',
    140,
    28,
    2,
    2,
    ARRAY['LUNCH', 'DINNER']::TEXT[],
    ARRAY['MAIN']::TEXT[],
    ARRAY['WEIGHT_LOSS', 'MAINTENANCE', 'MUSCLE_GAIN']::TEXT[],
    'STEAMED',
    'COMPONENT',
    '150g tôm hấp.'
  ),
  (
    64,
    'Xào',
    260,
    28,
    10,
    16,
    ARRAY['LUNCH', 'DINNER']::TEXT[],
    ARRAY['MAIN', 'SIDE']::TEXT[],
    ARRAY['WEIGHT_LOSS', 'MAINTENANCE', 'MUSCLE_GAIN']::TEXT[],
    'STIR_FRIED',
    'COMPONENT',
    '120g tôm + 200g bông cải, ít dầu.'
  ),
  (
    65,
    'Luộc',
    330,
    26,
    24,
    0,
    ARRAY['LUNCH', 'DINNER']::TEXT[],
    ARRAY['MAIN']::TEXT[],
    ARRAY['MAINTENANCE']::TEXT[],
    'BOILED',
    'COMPONENT',
    '120g thịt heo luộc nạc vừa.'
  ),
  (
    66,
    'Nướng',
    340,
    34,
    20,
    4,
    ARRAY['LUNCH', 'DINNER']::TEXT[],
    ARRAY['MAIN']::TEXT[],
    ARRAY['MAINTENANCE', 'MUSCLE_GAIN']::TEXT[],
    'GRILLED',
    'COMPONENT',
    '120g bò nướng.'
  ),
  (
    67,
    'Chay, Giảm cân',
    260,
    16,
    16,
    16,
    ARRAY['LUNCH', 'DINNER']::TEXT[],
    ARRAY['MAIN', 'SIDE']::TEXT[],
    ARRAY['WEIGHT_LOSS', 'MAINTENANCE']::TEXT[],
    'BRAISED',
    'COMPONENT',
    '180g đậu hũ sốt cà chua.'
  ),
  (
    68,
    'Đạm, Chay, Xào',
    280,
    18,
    17,
    14,
    ARRAY['LUNCH', 'DINNER']::TEXT[],
    ARRAY['MAIN', 'SIDE']::TEXT[],
    ARRAY['WEIGHT_LOSS', 'MAINTENANCE']::TEXT[],
    'STIR_FRIED',
    'COMPONENT',
    'Đậu hũ + nấm, ít dầu.'
  ),
  (
    69,
    'Chay, Xào, Rau',
    160,
    5,
    10,
    14,
    ARRAY['LUNCH', 'DINNER']::TEXT[],
    ARRAY['SIDE']::TEXT[],
    ARRAY['WEIGHT_LOSS', 'MAINTENANCE']::TEXT[],
    'STIR_FRIED',
    'COMPONENT',
    '200g rau muống xào tỏi, ít dầu.'
  ),
  (
    70,
    'Rau, Chay, Giảm Cân',
    60,
    4,
    0.5,
    10,
    ARRAY['LUNCH', 'DINNER']::TEXT[],
    ARRAY['SIDE']::TEXT[],
    ARRAY['WEIGHT_LOSS', 'MAINTENANCE']::TEXT[],
    'BOILED',
    'COMPONENT',
    '200g rau cải luộc.'
  ),
  (
    71,
    'Rau, Chay, Giảm Cân',
    80,
    6,
    0.5,
    14,
    ARRAY['LUNCH', 'DINNER']::TEXT[],
    ARRAY['SIDE']::TEXT[],
    ARRAY['WEIGHT_LOSS', 'MAINTENANCE']::TEXT[],
    'STEAMED',
    'COMPONENT',
    '200g bông cải hấp.'
  ),
  (
    72,
    'Ăn nhẹ, Giảm cân',
    180,
    13,
    14,
    1,
    ARRAY['BREAKFAST', 'LUNCH']::TEXT[],
    ARRAY['MAIN']::TEXT[],
    ARRAY['MAINTENANCE', 'MUSCLE_GAIN']::TEXT[],
    'FRIED',
    'COMPONENT',
    '2 trứng ốp la ít dầu.'
  ),
  (
    73,
    'Rau, Ăn nhẹ, Giảm cân',
    220,
    16,
    15,
    6,
    ARRAY['BREAKFAST', 'LUNCH', 'DINNER']::TEXT[],
    ARRAY['MAIN']::TEXT[],
    ARRAY['WEIGHT_LOSS', 'MAINTENANCE', 'MUSCLE_GAIN']::TEXT[],
    'FRIED',
    'COMPONENT',
    '2 trứng + rau, ít dầu.'
  ),
  (
    74,
    'Tráng miệng',
    180,
    9,
    7,
    20,
    ARRAY['SNACK', 'DESSERT']::TEXT[],
    ARRAY['SNACK', 'DESSERT']::TEXT[],
    ARRAY['WEIGHT_LOSS', 'MAINTENANCE']::TEXT[],
    'RAW',
    'LIGHT',
    'Sữa chua 120g + 10g chia.'
  ),
  (
    75,
    'Đồ uống',
    320,
    5,
    20,
    34,
    ARRAY['SNACK']::TEXT[],
    ARRAY['DRINK', 'DESSERT']::TEXT[],
    ARRAY['WEIGHT_GAIN', 'MAINTENANCE']::TEXT[],
    'RAW',
    'LIGHT',
    '1 ly vừa, hạn chế sữa đặc.'
  ),
  (
    76,
    'Đồ uống',
    240,
    8,
    5,
    44,
    ARRAY['BREAKFAST', 'SNACK']::TEXT[],
    ARRAY['DRINK', 'SNACK']::TEXT[],
    ARRAY['MAINTENANCE', 'WEIGHT_GAIN']::TEXT[],
    'RAW',
    'LIGHT',
    '1 ly chuối + sữa không đường.'
  ),
  (
    77,
    'Cháo, Tăng cân',
    360,
    24,
    8,
    50,
    ARRAY['BREAKFAST', 'DINNER']::TEXT[],
    ARRAY['MAIN', 'STAPLE']::TEXT[],
    ARRAY['WEIGHT_LOSS', 'MAINTENANCE']::TEXT[],
    'SOUP',
    'FULL_MEAL',
    '1 tô cháo gà rau củ.'
  ),
  (
    78,
    'Món nước',
    220,
    8,
    7,
    32,
    ARRAY['BREAKFAST', 'DINNER', 'SNACK']::TEXT[],
    ARRAY['SOUP', 'SIDE']::TEXT[],
    ARRAY['WEIGHT_LOSS', 'MAINTENANCE']::TEXT[],
    'SOUP',
    'LIGHT',
    '1 tô súp bí đỏ 300ml.'
  ),
  (
    79,
    'Món nước',
    180,
    7,
    5,
    28,
    ARRAY['DINNER', 'SNACK']::TEXT[],
    ARRAY['SOUP', 'SIDE']::TEXT[],
    ARRAY['WEIGHT_LOSS', 'MAINTENANCE']::TEXT[],
    'SOUP',
    'LIGHT',
    '1 tô súp rau củ 300ml.'
  ),
  (
    82,
    'Ăn nhẹ',
    300,
    18,
    8,
    38,
    ARRAY['SNACK', 'LUNCH', 'DINNER']::TEXT[],
    ARRAY['SNACK', 'SIDE']::TEXT[],
    ARRAY['WEIGHT_LOSS', 'MAINTENANCE']::TEXT[],
    'RAW',
    'LIGHT',
    '3 cuốn tôm thịt.'
  ),
  (
    83,
    'Gỏi, Rau. Giảm cân',
    280,
    28,
    10,
    18,
    ARRAY['LUNCH', 'DINNER']::TEXT[],
    ARRAY['MAIN', 'SIDE']::TEXT[],
    ARRAY['WEIGHT_LOSS', 'MAINTENANCE', 'MUSCLE_GAIN']::TEXT[],
    'RAW',
    'FULL_MEAL',
    '120g gà xé + bắp cải + ít sốt.'
  ),
  (
    84,
    'Kho, Tăng cân',
    330,
    28,
    18,
    10,
    ARRAY['LUNCH', 'DINNER']::TEXT[],
    ARRAY['MAIN']::TEXT[],
    ARRAY['MAINTENANCE', 'MUSCLE_GAIN']::TEXT[],
    'BRAISED',
    'COMPONENT',
    '120g cá kho, chưa tính cơm.'
  ),
  (
    85,
    'Kho',
    420,
    24,
    32,
    8,
    ARRAY['LUNCH', 'DINNER']::TEXT[],
    ARRAY['MAIN']::TEXT[],
    ARRAY['MAINTENANCE', 'WEIGHT_GAIN']::TEXT[],
    'BRAISED',
    'COMPONENT',
    '120g thịt kho tiêu, béo cao.'
  ),
  (
    86,
    'Tăng cân',
    420,
    32,
    24,
    18,
    ARRAY['LUNCH', 'DINNER']::TEXT[],
    ARRAY['MAIN']::TEXT[],
    ARRAY['MAINTENANCE', 'MUSCLE_GAIN']::TEXT[],
    'STIR_FRIED',
    'COMPONENT',
    '120g bò + rau/củ, chưa tính cơm.'
  ),
  (
    87,
    'Cơm',
    680,
    22,
    24,
    92,
    ARRAY['LUNCH', 'DINNER']::TEXT[],
    ARRAY['MAIN', 'STAPLE']::TEXT[],
    ARRAY['WEIGHT_GAIN', 'MAINTENANCE']::TEXT[],
    'FRIED',
    'FULL_MEAL',
    '1 đĩa cơm chiên vừa, dầu cao.'
  ),
  (
    88,
    'Cơm',
    720,
    24,
    26,
    96,
    ARRAY['LUNCH', 'DINNER']::TEXT[],
    ARRAY['MAIN', 'STAPLE']::TEXT[],
    ARRAY['WEIGHT_GAIN', 'MAINTENANCE']::TEXT[],
    'FRIED',
    'FULL_MEAL',
    '1 đĩa vừa, natri cao.'
  ),
  (
    91,
    'Bún',
    500,
    25,
    14,
    68,
    ARRAY['BREAKFAST', 'LUNCH']::TEXT[],
    ARRAY['MAIN', 'STAPLE']::TEXT[],
    ARRAY['MAINTENANCE']::TEXT[],
    'SOUP',
    'FULL_MEAL',
    '1 tô bún mọc vừa.'
  ),
  (
    92,
    'Bún',
    480,
    28,
    10,
    66,
    ARRAY['BREAKFAST', 'LUNCH', 'DINNER']::TEXT[],
    ARRAY['MAIN', 'STAPLE']::TEXT[],
    ARRAY['WEIGHT_LOSS', 'MAINTENANCE']::TEXT[],
    'SOUP',
    'FULL_MEAL',
    '1 tô vừa.'
  ),
  (
    93,
    'Bún',
    420,
    16,
    10,
    68,
    ARRAY['BREAKFAST', 'LUNCH', 'DINNER']::TEXT[],
    ARRAY['MAIN', 'STAPLE']::TEXT[],
    ARRAY['WEIGHT_LOSS', 'MAINTENANCE']::TEXT[],
    'SOUP',
    'FULL_MEAL',
    '1 tô bún chay vừa, có đậu hũ.'
  ),
  (
    94,
    'Cơm',
    650,
    14,
    30,
    84,
    ARRAY['SNACK', 'LUNCH']::TEXT[],
    ARRAY['SNACK', 'STAPLE']::TEXT[],
    ARRAY['WEIGHT_GAIN', 'MAINTENANCE']::TEXT[],
    'FRIED',
    'LIGHT',
    '1 phần vừa, dầu/mỡ và natri cao.'
  ),
  (
    95,
    'Kho, Giảm cân',
    300,
    32,
    12,
    14,
    ARRAY['LUNCH', 'DINNER']::TEXT[],
    ARRAY['MAIN']::TEXT[],
    ARRAY['WEIGHT_LOSS', 'MAINTENANCE', 'MUSCLE_GAIN']::TEXT[],
    'BRAISED',
    'COMPONENT',
    '120g cá ngừ kho dưa.'
  ),
  (
    96,
    'Xào, Tăng cân',
    350,
    32,
    20,
    8,
    ARRAY['LUNCH', 'DINNER']::TEXT[],
    ARRAY['MAIN']::TEXT[],
    ARRAY['MAINTENANCE', 'MUSCLE_GAIN']::TEXT[],
    'STIR_FRIED',
    'COMPONENT',
    '120g gà xào, ít dầu.'
  ),
  (
    97,
    'Xào, Giảm cân',
    330,
    32,
    18,
    12,
    ARRAY['LUNCH', 'DINNER']::TEXT[],
    ARRAY['MAIN', 'SIDE']::TEXT[],
    ARRAY['WEIGHT_LOSS', 'MAINTENANCE', 'MUSCLE_GAIN']::TEXT[],
    'STIR_FRIED',
    'COMPONENT',
    '120g bò + cần tây.'
  ),
  (
    98,
    'Tăng cân',
    420,
    28,
    26,
    16,
    ARRAY['LUNCH', 'DINNER']::TEXT[],
    ARRAY['MAIN']::TEXT[],
    ARRAY['MAINTENANCE', 'WEIGHT_GAIN']::TEXT[],
    'BRAISED',
    'COMPONENT',
    'Thịt băm + đậu hũ, 1 phần vừa.'
  ),
  (
    99,
    'Món nước',
    360,
    18,
    10,
    50,
    ARRAY['LUNCH', 'DINNER']::TEXT[],
    ARRAY['MAIN', 'SOUP']::TEXT[],
    ARRAY['WEIGHT_LOSS', 'MAINTENANCE']::TEXT[],
    'SOUP',
    'FULL_MEAL',
    '1 khẩu phần cá nhân, thêm ít bún.'
  ),
  (
    100,
    'Món nước',
    540,
    35,
    18,
    56,
    ARRAY['LUNCH', 'DINNER']::TEXT[],
    ARRAY['MAIN', 'SOUP']::TEXT[],
    ARRAY['MAINTENANCE', 'MUSCLE_GAIN']::TEXT[],
    'SOUP',
    'FULL_MEAL',
    '1 khẩu phần cá nhân, tính ít bún.'
  ),
  (
    101,
    'Món nước',
    520,
    38,
    12,
    58,
    ARRAY['LUNCH', 'DINNER']::TEXT[],
    ARRAY['MAIN', 'SOUP']::TEXT[],
    ARRAY['MAINTENANCE', 'MUSCLE_GAIN']::TEXT[],
    'SOUP',
    'FULL_MEAL',
    '1 khẩu phần cá nhân.'
  ),
  (
    102,
    'Món nước',
    480,
    34,
    10,
    58,
    ARRAY['LUNCH', 'DINNER']::TEXT[],
    ARRAY['MAIN', 'SOUP']::TEXT[],
    ARRAY['WEIGHT_LOSS', 'MAINTENANCE', 'MUSCLE_GAIN']::TEXT[],
    'SOUP',
    'FULL_MEAL',
    '1 khẩu phần cá nhân.'
  ),
  (
    103,
    'Hấp, Giảm cân',
    170,
    30,
    3,
    4,
    ARRAY['LUNCH', 'DINNER']::TEXT[],
    ARRAY['MAIN']::TEXT[],
    ARRAY['WEIGHT_LOSS', 'MAINTENANCE', 'MUSCLE_GAIN']::TEXT[],
    'STEAMED',
    'COMPONENT',
    '150g mực hấp.'
  ),
  (
    104,
    'Xào',
    260,
    30,
    10,
    12,
    ARRAY['LUNCH', 'DINNER']::TEXT[],
    ARRAY['MAIN', 'SIDE']::TEXT[],
    ARRAY['WEIGHT_LOSS', 'MAINTENANCE', 'MUSCLE_GAIN']::TEXT[],
    'STIR_FRIED',
    'COMPONENT',
    '150g mực + cần, ít dầu.'
  ),
  (
    105,
    'Rim',
    280,
    28,
    10,
    18,
    ARRAY['LUNCH', 'DINNER']::TEXT[],
    ARRAY['MAIN']::TEXT[],
    ARRAY['MAINTENANCE', 'MUSCLE_GAIN']::TEXT[],
    'BRAISED',
    'COMPONENT',
    '150g tôm rim, có đường/nước mắm.'
  ),
  (
    106,
    'Món nước',
    230,
    18,
    6,
    28,
    ARRAY['BREAKFAST', 'SNACK', 'DINNER']::TEXT[],
    ARRAY['SOUP', 'SNACK']::TEXT[],
    ARRAY['WEIGHT_LOSS', 'MAINTENANCE']::TEXT[],
    'SOUP',
    'LIGHT',
    '1 chén/tô nhỏ 300ml.'
  ),
  (
    107,
    'Cháo',
    340,
    24,
    6,
    52,
    ARRAY['BREAKFAST', 'DINNER']::TEXT[],
    ARRAY['MAIN', 'STAPLE']::TEXT[],
    ARRAY['WEIGHT_LOSS', 'MAINTENANCE']::TEXT[],
    'SOUP',
    'FULL_MEAL',
    '1 tô cháo tôm.'
  ),
  (
    108,
    'Cháo, Tăng cân',
    420,
    26,
    16,
    50,
    ARRAY['BREAKFAST', 'DINNER']::TEXT[],
    ARRAY['MAIN', 'STAPLE']::TEXT[],
    ARRAY['MAINTENANCE', 'MUSCLE_GAIN']::TEXT[],
    'SOUP',
    'FULL_MEAL',
    '1 tô cháo cá hồi.'
  ),
  (
    109,
    'Cơm',
    600,
    34,
    20,
    70,
    ARRAY['LUNCH', 'DINNER']::TEXT[],
    ARRAY['MAIN', 'STAPLE']::TEXT[],
    ARRAY['MAINTENANCE', 'MUSCLE_GAIN']::TEXT[],
    'RAW',
    'FULL_MEAL',
    'Cơm 150g + cá hồi + rong biển.'
  ),
  (
    110,
    'Cơm',
    780,
    32,
    32,
    88,
    ARRAY['LUNCH', 'DINNER']::TEXT[],
    ARRAY['MAIN', 'STAPLE']::TEXT[],
    ARRAY['WEIGHT_GAIN', 'MAINTENANCE']::TEXT[],
    'GRILLED',
    'FULL_MEAL',
    'Cơm + sườn nướng mật ong, đường/dầu cao.'
  ),
  (
    111,
    'Mì/Miến/Nui',
    520,
    28,
    16,
    66,
    ARRAY['BREAKFAST', 'LUNCH']::TEXT[],
    ARRAY['MAIN', 'STAPLE']::TEXT[],
    ARRAY['MAINTENANCE']::TEXT[],
    'SOUP',
    'FULL_MEAL',
    '1 tô mì trứng gà.'
  ),
  (
    112,
    'Mì/Miến/Nui',
    680,
    32,
    24,
    82,
    ARRAY['LUNCH', 'DINNER']::TEXT[],
    ARRAY['MAIN', 'STAPLE']::TEXT[],
    ARRAY['WEIGHT_GAIN', 'MAINTENANCE']::TEXT[],
    'STIR_FRIED',
    'FULL_MEAL',
    '1 đĩa mì xào bò.'
  ),
  (
    113,
    'Xào',
    720,
    34,
    26,
    88,
    ARRAY['LUNCH', 'DINNER']::TEXT[],
    ARRAY['MAIN', 'STAPLE']::TEXT[],
    ARRAY['WEIGHT_GAIN', 'MAINTENANCE']::TEXT[],
    'STIR_FRIED',
    'FULL_MEAL',
    '1 đĩa phở xào bò, dầu cao.'
  ),
  (
    114,
    'Mì/Miến/Nui',
    690,
    34,
    24,
    84,
    ARRAY['LUNCH', 'DINNER']::TEXT[],
    ARRAY['MAIN', 'STAPLE']::TEXT[],
    ARRAY['WEIGHT_GAIN', 'MAINTENANCE']::TEXT[],
    'STIR_FRIED',
    'FULL_MEAL',
    '1 đĩa nui xào bò.'
  ),
  (
    115,
    'Món nước',
    540,
    26,
    16,
    72,
    ARRAY['BREAKFAST', 'LUNCH']::TEXT[],
    ARRAY['MAIN', 'STAPLE']::TEXT[],
    ARRAY['MAINTENANCE']::TEXT[],
    'SOUP',
    'FULL_MEAL',
    '1 tô bánh đa cua.'
  ),
  (
    116,
    'Món nước',
    560,
    28,
    16,
    76,
    ARRAY['BREAKFAST', 'LUNCH']::TEXT[],
    ARRAY['MAIN', 'STAPLE']::TEXT[],
    ARRAY['MAINTENANCE']::TEXT[],
    'SOUP',
    'FULL_MEAL',
    '1 tô bánh canh cua.'
  ),
  (
    117,
    'Món nước',
    720,
    28,
    34,
    72,
    ARRAY['LUNCH', 'DINNER']::TEXT[],
    ARRAY['MAIN', 'STAPLE']::TEXT[],
    ARRAY['WEIGHT_GAIN', 'MAINTENANCE']::TEXT[],
    'SOUP',
    'FULL_MEAL',
    '1 tô vừa, giò heo béo cao.'
  ),
  (
    118,
    'Món nước',
    520,
    28,
    12,
    74,
    ARRAY['BREAKFAST', 'LUNCH']::TEXT[],
    ARRAY['MAIN', 'STAPLE']::TEXT[],
    ARRAY['MAINTENANCE']::TEXT[],
    'SOUP',
    'FULL_MEAL',
    '1 tô bánh canh gà.'
  ),
  (
    119,
    'Xôi, Tăng cân',
    650,
    30,
    20,
    86,
    ARRAY['BREAKFAST', 'LUNCH']::TEXT[],
    ARRAY['MAIN', 'STAPLE']::TEXT[],
    ARRAY['WEIGHT_GAIN', 'MAINTENANCE']::TEXT[],
    'STEAMED',
    'FULL_MEAL',
    '1 phần xôi gà vừa.'
  ),
  (
    120,
    'Ăn nhẹ',
    500,
    14,
    10,
    88,
    ARRAY['BREAKFAST', 'SNACK']::TEXT[],
    ARRAY['STAPLE', 'SNACK']::TEXT[],
    ARRAY['WEIGHT_GAIN', 'MAINTENANCE']::TEXT[],
    'STEAMED',
    'FULL_MEAL',
    '1 phần xôi đậu xanh vừa.'
  ),
  (
    123,
    'Bún',
    580,
    30,
    20,
    68,
    ARRAY['BREAKFAST', 'LUNCH']::TEXT[],
    ARRAY['MAIN', 'STAPLE']::TEXT[],
    ARRAY['MAINTENANCE', 'WEIGHT_GAIN']::TEXT[],
    'SOUP',
    'FULL_MEAL',
    '1 tô bún mọc sườn.'
  ),
  (
    124,
    'Bún',
    600,
    32,
    22,
    68,
    ARRAY['BREAKFAST', 'LUNCH']::TEXT[],
    ARRAY['MAIN', 'STAPLE']::TEXT[],
    ARRAY['MAINTENANCE', 'WEIGHT_GAIN']::TEXT[],
    'SOUP',
    'FULL_MEAL',
    '1 tô bún sườn non.'
  ),
  (
    127,
    'Cơm',
    670,
    28,
    22,
    90,
    ARRAY['LUNCH', 'DINNER']::TEXT[],
    ARRAY['MAIN', 'STAPLE']::TEXT[],
    ARRAY['WEIGHT_GAIN', 'MAINTENANCE']::TEXT[],
    'FRIED',
    'FULL_MEAL',
    '1 đĩa cơm chiên tôm vừa.'
  ),
  (
    128,
    'Cơm',
    500,
    22,
    16,
    68,
    ARRAY['LUNCH', 'DINNER']::TEXT[],
    ARRAY['MAIN', 'STAPLE']::TEXT[],
    ARRAY['WEIGHT_LOSS', 'MAINTENANCE']::TEXT[],
    'BRAISED',
    'FULL_MEAL',
    '150g cơm + đậu hũ + rau.'
  ),
  (
    129,
    'Cơm',
    520,
    18,
    14,
    78,
    ARRAY['LUNCH', 'DINNER']::TEXT[],
    ARRAY['MAIN', 'STAPLE']::TEXT[],
    ARRAY['WEIGHT_LOSS', 'MAINTENANCE']::TEXT[],
    'STIR_FRIED',
    'FULL_MEAL',
    'Cơm + nấm + rau + đậu/đạm chay.'
  ),
  (
    130,
    'Cơm',
    850,
    34,
    38,
    90,
    ARRAY['LUNCH', 'DINNER']::TEXT[],
    ARRAY['MAIN', 'STAPLE']::TEXT[],
    ARRAY['WEIGHT_GAIN']::TEXT[],
    'FRIED',
    'FULL_MEAL',
    'Cơm + gà xối mỡ, dầu/mỡ cao.'
  );

-- Preview rows that will be updated.
SELECT
  f.id,
  f.name,
  f.category AS old_category,
  u.category AS new_category,
  f.calories AS old_calories,
  u.calories AS new_calories,
  f.protein AS old_protein,
  u.protein AS new_protein,
  f.fat AS old_fat,
  u.fat AS new_fat,
  f.carbs AS old_carbs,
  u.carbs AS new_carbs,
  f."mealTimeTags" AS old_meal_time_tags,
  u.meal_time_tags AS new_meal_time_tags,
  u.serving_note
FROM "food_items" f
JOIN food_nutrition_updates u ON u.id = f.id
ORDER BY f.id;

-- Rows in CSV that do not exist in DB.
SELECT u.id AS unmatched_update_id
FROM food_nutrition_updates u
LEFT JOIN "food_items" f ON f.id = u.id
WHERE f.id IS NULL
ORDER BY u.id;

UPDATE "food_items" f
SET
  category = COALESCE(u.category, f.category),
  calories = u.calories,
  protein = u.protein,
  fat = u.fat,
  carbs = u.carbs,
  "mealTimeTags" = u.meal_time_tags,
  "mealRoles" = u.meal_roles,
  "goalTags" = u.goal_tags,
  "cookingMethod" = u.cooking_method,
  "portionType" = u.portion_type,
  "updatedAt" = NOW()
FROM food_nutrition_updates u
WHERE f.id = u.id;

-- Verify changed rows after update.
SELECT
  f.id,
  f.name,
  f.category,
  f.calories,
  f.protein,
  f.fat,
  f.carbs,
  f."mealTimeTags",
  f."mealRoles",
  f."goalTags",
  f."cookingMethod",
  f."portionType",
  f."updatedAt"
FROM "food_items" f
JOIN food_nutrition_updates u ON u.id = f.id
ORDER BY f.id;

COMMIT;
