import { Request, Response } from 'express';
import prisma from '../lib/prisma';

type DbTableColumn = {
  columnName: string;
  dataType: string;
  udtName: string;
  isNullable: boolean;
  columnDefault: string | null;
  ordinal: number;
  isIdentity: boolean;
  isPrimaryKey: boolean;
};

const IDENTIFIER_REGEX = /^[A-Za-z_][A-Za-z0-9_]*$/;
const EXCLUDED_TABLES = new Set(['_prisma_migrations']);
const DEFAULT_PAGE_SIZE = 30;
const MAX_PAGE_SIZE = 200;
const MAX_QUERY_ROWS = 300;

const toPositiveInt = (value: unknown, fallback: number, min: number, max: number) => {
  const parsed = Number.parseInt(String(value ?? ''), 10);
  if (!Number.isFinite(parsed) || parsed < min) return fallback;
  return Math.min(max, parsed);
};

const isSafeIdentifier = (value: string) => IDENTIFIER_REGEX.test(value);

const quoteIdentifier = (value: string) => `"${value.replace(/"/g, '""')}"`;

const getTableNameFromReq = (req: Request) => String(req.params.table || '').trim();

const getPublicTables = async () => {
  const rows = await prisma.$queryRawUnsafe<Array<{ name: string; rowEstimate: bigint | number | null }>>(
    `
      SELECT
        t.table_name AS "name",
        COALESCE(s.n_live_tup::bigint, 0) AS "rowEstimate"
      FROM information_schema.tables t
      LEFT JOIN pg_stat_user_tables s ON s.relname = t.table_name
      WHERE t.table_schema = 'public'
        AND t.table_type = 'BASE TABLE'
      ORDER BY t.table_name ASC
    `,
  );

  return rows
    .filter((row) => !EXCLUDED_TABLES.has(row.name))
    .map((row) => ({
      name: row.name,
      rowEstimate: Number(row.rowEstimate || 0),
    }));
};

const getTableColumns = async (tableName: string): Promise<DbTableColumn[]> => {
  const columns = await prisma.$queryRawUnsafe<Array<{
    columnName: string;
    dataType: string;
    udtName: string;
    isNullable: boolean;
    columnDefault: string | null;
    ordinal: number;
    isIdentity: boolean;
  }>>(
    `
      SELECT
        c.column_name AS "columnName",
        c.data_type AS "dataType",
        c.udt_name AS "udtName",
        CASE WHEN c.is_nullable = 'YES' THEN true ELSE false END AS "isNullable",
        c.column_default AS "columnDefault",
        c.ordinal_position AS "ordinal",
        CASE WHEN c.is_identity = 'YES' THEN true ELSE false END AS "isIdentity"
      FROM information_schema.columns c
      WHERE c.table_schema = 'public'
        AND c.table_name = $1
      ORDER BY c.ordinal_position ASC
    `,
    tableName,
  );

  const pkRows = await prisma.$queryRawUnsafe<Array<{ columnName: string }>>(
    `
      SELECT a.attname AS "columnName"
      FROM pg_index i
      JOIN pg_class t ON t.oid = i.indrelid
      JOIN pg_namespace n ON n.oid = t.relnamespace
      JOIN pg_attribute a ON a.attrelid = t.oid AND a.attnum = ANY(i.indkey)
      WHERE i.indisprimary = true
        AND n.nspname = 'public'
        AND t.relname = $1
    `,
    tableName,
  );

  const pkSet = new Set(pkRows.map((row) => row.columnName));

  return columns.map((column) => ({
    ...column,
    isPrimaryKey: pkSet.has(column.columnName),
  }));
};

const resolveTableOrFail = async (req: Request, res: Response) => {
  const tableName = getTableNameFromReq(req);
  if (!tableName || !isSafeIdentifier(tableName)) {
    res.status(400).json({ error: 'Invalid table name' });
    return null;
  }

  const tables = await getPublicTables();
  const found = tables.find((table) => table.name === tableName);
  if (!found) {
    res.status(404).json({ error: 'Table not found' });
    return null;
  }

  const columns = await getTableColumns(tableName);
  if (columns.length === 0) {
    res.status(404).json({ error: 'Table metadata not found' });
    return null;
  }

  const pkColumns = columns.filter((column) => column.isPrimaryKey);

  return {
    tableName,
    tableInfo: found,
    columns,
    pkColumns,
    hasSinglePrimaryKey: pkColumns.length === 1,
    primaryKeyColumn: pkColumns.length === 1 ? pkColumns[0].columnName : null,
  };
};

const isAutoGeneratedColumn = (column: DbTableColumn) => {
  if (column.isIdentity) return true;
  const def = String(column.columnDefault || '').toLowerCase();
  if (!def) return false;
  return def.includes('nextval(') || def.includes('generated');
};

const coerceValueByColumn = (value: unknown, column: DbTableColumn) => {
  if (value === null || value === undefined) return null;

  const udt = column.udtName;
  if (['int2', 'int4', 'int8', 'float4', 'float8', 'numeric'].includes(udt)) {
    const num = Number(value);
    return Number.isFinite(num) ? num : value;
  }

  if (udt === 'bool') {
    if (typeof value === 'boolean') return value;
    if (typeof value === 'string') {
      const normalized = value.trim().toLowerCase();
      if (normalized === 'true') return true;
      if (normalized === 'false') return false;
    }
  }

  if (udt === 'json' || udt === 'jsonb') {
    if (typeof value === 'string') {
      try {
        return JSON.parse(value);
      } catch {
        return value;
      }
    }
    return value;
  }

  return value;
};

export const getDbTables = async (req: Request, res: Response) => {
  try {
    const tables = await getPublicTables();
    res.json({ success: true, data: tables });
  } catch (error: any) {
    res.status(500).json({ error: error.message });
  }
};

export const getDbTableSchema = async (req: Request, res: Response) => {
  try {
    const resolved = await resolveTableOrFail(req, res);
    if (!resolved) return;

    res.json({
      success: true,
      data: {
        table: resolved.tableName,
        rowEstimate: resolved.tableInfo.rowEstimate,
        columns: resolved.columns,
        hasSinglePrimaryKey: resolved.hasSinglePrimaryKey,
        primaryKeyColumn: resolved.primaryKeyColumn,
      },
    });
  } catch (error: any) {
    res.status(500).json({ error: error.message });
  }
};

export const getDbTableRows = async (req: Request, res: Response) => {
  try {
    const resolved = await resolveTableOrFail(req, res);
    if (!resolved) return;

    const page = toPositiveInt(req.query.page, 1, 1, 1_000_000);
    const limit = toPositiveInt(req.query.limit, DEFAULT_PAGE_SIZE, 1, MAX_PAGE_SIZE);
    const offset = (page - 1) * limit;
    const search = String(req.query.search || '').trim();
    const sortByRaw = String(req.query.sortBy || '').trim();
    const sortOrderRaw = String(req.query.sortOrder || 'desc').trim().toLowerCase();

    const sortableColumns = new Set(resolved.columns.map((column) => column.columnName));
    const fallbackSort = resolved.primaryKeyColumn || resolved.columns[0].columnName;
    const sortBy = sortableColumns.has(sortByRaw) ? sortByRaw : fallbackSort;
    const sortOrder = sortOrderRaw === 'asc' ? 'ASC' : 'DESC';

    const tableRef = `${quoteIdentifier('public')}.${quoteIdentifier(resolved.tableName)}`;
    const selectedColumns = resolved.columns.map((column) => quoteIdentifier(column.columnName)).join(', ');

    const whereParams: unknown[] = [];
    let whereClause = '';

    if (search) {
      const searchColumns = resolved.columns;
      const parts = searchColumns.map((column, idx) => {
        whereParams.push(`%${search}%`);
        return `CAST(${quoteIdentifier(column.columnName)} AS TEXT) ILIKE $${idx + 1}`;
      });
      whereClause = ` WHERE (${parts.join(' OR ')})`;
    }

    const countQuery = `SELECT COUNT(*)::int AS "count" FROM ${tableRef}${whereClause}`;
    const countRows = await prisma.$queryRawUnsafe<Array<{ count: number }>>(countQuery, ...whereParams);
    const total = Number(countRows[0]?.count || 0);

    const limitPlaceholder = whereParams.length + 1;
    const offsetPlaceholder = whereParams.length + 2;

    const rowsQuery = `
      SELECT ${selectedColumns}
      FROM ${tableRef}
      ${whereClause}
      ORDER BY ${quoteIdentifier(sortBy)} ${sortOrder}
      LIMIT $${limitPlaceholder} OFFSET $${offsetPlaceholder}
    `;

    const rows = await prisma.$queryRawUnsafe<any[]>(rowsQuery, ...whereParams, limit, offset);

    res.json({
      success: true,
      data: {
        table: resolved.tableName,
        rowEstimate: resolved.tableInfo.rowEstimate,
        columns: resolved.columns,
        hasSinglePrimaryKey: resolved.hasSinglePrimaryKey,
        primaryKeyColumn: resolved.primaryKeyColumn,
        rows,
        pagination: {
          page,
          limit,
          total,
          totalPages: Math.max(1, Math.ceil(total / limit)),
        },
      },
    });
  } catch (error: any) {
    res.status(500).json({ error: error.message });
  }
};

export const createDbTableRow = async (req: Request, res: Response) => {
  try {
    const resolved = await resolveTableOrFail(req, res);
    if (!resolved) return;

    const payload = req.body?.values ?? req.body;
    if (!payload || typeof payload !== 'object' || Array.isArray(payload)) {
      return res.status(400).json({ error: 'values must be an object' });
    }

    const allowedColumns = new Set(
      resolved.columns
        .filter((column) => !isAutoGeneratedColumn(column))
        .map((column) => column.columnName),
    );

    const entries = Object.entries(payload as Record<string, unknown>);
    for (const [key] of entries) {
      if (!allowedColumns.has(key)) {
        return res.status(400).json({ error: `Column not writable: ${key}` });
      }
    }

    const tableRef = `${quoteIdentifier('public')}.${quoteIdentifier(resolved.tableName)}`;

    let insertedRows: any[] = [];
    if (entries.length === 0) {
      insertedRows = await prisma.$queryRawUnsafe<any[]>(`INSERT INTO ${tableRef} DEFAULT VALUES RETURNING *`);
    } else {
      const cols = entries.map(([key]) => quoteIdentifier(key)).join(', ');
      const placeholders = entries.map((_, idx) => `$${idx + 1}`).join(', ');
      const values = entries.map(([key, value]) => {
        const column = resolved.columns.find((item) => item.columnName === key)!;
        return coerceValueByColumn(value, column);
      });

      insertedRows = await prisma.$queryRawUnsafe<any[]>(
        `INSERT INTO ${tableRef} (${cols}) VALUES (${placeholders}) RETURNING *`,
        ...values,
      );
    }

    return res.status(201).json({ success: true, data: insertedRows[0] || null });
  } catch (error: any) {
    return res.status(500).json({ error: error.message });
  }
};

export const updateDbTableRow = async (req: Request, res: Response) => {
  try {
    const resolved = await resolveTableOrFail(req, res);
    if (!resolved) return;

    if (!resolved.hasSinglePrimaryKey || !resolved.primaryKeyColumn) {
      return res.status(400).json({ error: 'This table has no single primary key for safe update' });
    }

    const rowId = String(req.params.rowId || '').trim();
    if (!rowId) return res.status(400).json({ error: 'Missing row id' });

    const payload = req.body?.values ?? req.body;
    if (!payload || typeof payload !== 'object' || Array.isArray(payload)) {
      return res.status(400).json({ error: 'values must be an object' });
    }

    const allowedColumns = new Set(
      resolved.columns
        .filter((column) => column.columnName !== resolved.primaryKeyColumn)
        .filter((column) => !isAutoGeneratedColumn(column))
        .map((column) => column.columnName),
    );

    const entries = Object.entries(payload as Record<string, unknown>).filter(([key]) => key !== resolved.primaryKeyColumn);
    if (entries.length === 0) {
      return res.status(400).json({ error: 'No updatable columns provided' });
    }

    for (const [key] of entries) {
      if (!allowedColumns.has(key)) {
        return res.status(400).json({ error: `Column not writable: ${key}` });
      }
    }

    const tableRef = `${quoteIdentifier('public')}.${quoteIdentifier(resolved.tableName)}`;
    const setClause = entries
      .map(([key], idx) => `${quoteIdentifier(key)} = $${idx + 1}`)
      .join(', ');

    const setValues = entries.map(([key, value]) => {
      const column = resolved.columns.find((item) => item.columnName === key)!;
      return coerceValueByColumn(value, column);
    });

    const pkColumn = resolved.columns.find((item) => item.columnName === resolved.primaryKeyColumn)!;
    const pkValue = coerceValueByColumn(rowId, pkColumn);

    const updatedRows = await prisma.$queryRawUnsafe<any[]>(
      `
        UPDATE ${tableRef}
        SET ${setClause}
        WHERE ${quoteIdentifier(resolved.primaryKeyColumn)} = $${entries.length + 1}
        RETURNING *
      `,
      ...setValues,
      pkValue,
    );

    if (!updatedRows.length) return res.status(404).json({ error: 'Row not found' });

    return res.json({ success: true, data: updatedRows[0] });
  } catch (error: any) {
    return res.status(500).json({ error: error.message });
  }
};

export const deleteDbTableRow = async (req: Request, res: Response) => {
  try {
    const resolved = await resolveTableOrFail(req, res);
    if (!resolved) return;

    if (!resolved.hasSinglePrimaryKey || !resolved.primaryKeyColumn) {
      return res.status(400).json({ error: 'This table has no single primary key for safe delete' });
    }

    const rowId = String(req.params.rowId || '').trim();
    if (!rowId) return res.status(400).json({ error: 'Missing row id' });

    const pkColumn = resolved.columns.find((item) => item.columnName === resolved.primaryKeyColumn)!;
    const pkValue = coerceValueByColumn(rowId, pkColumn);

    const tableRef = `${quoteIdentifier('public')}.${quoteIdentifier(resolved.tableName)}`;
    const deletedRows = await prisma.$queryRawUnsafe<any[]>(
      `
        DELETE FROM ${tableRef}
        WHERE ${quoteIdentifier(resolved.primaryKeyColumn)} = $1
        RETURNING *
      `,
      pkValue,
    );

    if (!deletedRows.length) return res.status(404).json({ error: 'Row not found' });

    return res.json({ success: true, data: deletedRows[0] });
  } catch (error: any) {
    return res.status(500).json({ error: error.message });
  }
};

export const executeDbSelectQuery = async (req: Request, res: Response) => {
  try {
    const rawQuery = String(req.body?.query || '').trim();
    const limit = toPositiveInt(req.body?.limit, 100, 1, MAX_QUERY_ROWS);

    if (!rawQuery) return res.status(400).json({ error: 'query is required' });

    const normalized = rawQuery.replace(/;+\s*$/g, '');
    if (!normalized) return res.status(400).json({ error: 'query is required' });
    if (normalized.includes(';')) return res.status(400).json({ error: 'Only single-statement query is allowed' });

    const lower = normalized.toLowerCase();
    const startsValid = lower.startsWith('select ') || lower.startsWith('with ') || lower.startsWith('explain ');
    if (!startsValid) {
      return res.status(400).json({ error: 'Only SELECT/WITH/EXPLAIN SELECT queries are allowed' });
    }

    const forbidden = /\b(insert|update|delete|drop|alter|create|truncate|grant|revoke|comment|copy)\b/i;
    if (forbidden.test(lower)) {
      return res.status(400).json({ error: 'Query contains forbidden keyword' });
    }

    const startedAt = Date.now();
    const wrapped = `SELECT * FROM (${normalized}) AS ${quoteIdentifier('__query_result')} LIMIT $1`;
    const rows = await prisma.$queryRawUnsafe<any[]>(wrapped, limit);
    const durationMs = Date.now() - startedAt;

    const columns = rows.length > 0 ? Object.keys(rows[0]) : [];

    return res.json({
      success: true,
      data: {
        columns,
        rows,
        rowCount: rows.length,
        limit,
        durationMs,
      },
    });
  } catch (error: any) {
    return res.status(400).json({ error: error.message || 'Query execution failed' });
  }
};
