ALTER TABLE "food_items"
ADD COLUMN "mealTimeTags" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
ADD COLUMN "mealRoles" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
ADD COLUMN "goalTags" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
ADD COLUMN "cookingMethod" TEXT,
ADD COLUMN "portionType" TEXT;
